---
- name: instalando meu jenkins 
  hosts: automation
  tasks:
    - name: instalando deps
      package:
       name:
        - java
        - wget
    
      
    - name: instalando o repositorio do jenkins
      shell: "wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo " 
    - name: adicionando chave
      shell: "rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key"
    
    - name: instalndo o jenkins
      package:
       name:
        - jenkins
